// <auto-generated />
namespace QLBS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_2_tableê : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_2_tableê));
        
        string IMigrationMetadata.Id
        {
            get { return "202112140841417_create_2_tableê"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
