// <auto-generated />
namespace QLBS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_acc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_acc));
        
        string IMigrationMetadata.Id
        {
            get { return "202112140853014_create_acc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
